"""initial: create users and leads tables

Revision ID: ae61ccfb38b4
Revises: 
Create Date: 2026-07-01 20:23:55.842631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae61ccfb38b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'REACHED_OUT', name='lead_state'), server_default='PENDING', nullable=False),
    sa.Column('resume_path', sa.String(length=1024), nullable=False),
    sa.Column('resume_original_name', sa.String(length=512), nullable=False),
    sa.Column('resume_content_type', sa.String(length=255), nullable=False),
    sa.Column('resume_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('leads')
    # Postgres does not drop the enum type with the table; drop it explicitly so
    # a downgrade->upgrade cycle re-runs cleanly.
    sa.Enum(name='lead_state').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
